# Generated by Django 3.2.3 on 2021-06-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='db_host',
            field=models.CharField(help_text='ex: localhost/85.64.34.21', max_length=100),
        ),
        migrations.AlterField(
            model_name='db',
            name='db_login_password',
            field=models.CharField(blank=True, help_text='database password', max_length=100),
        ),
        migrations.AlterField(
            model_name='db',
            name='db_login_username',
            field=models.CharField(help_text='database username', max_length=255),
        ),
        migrations.AlterField(
            model_name='db',
            name='db_name',
            field=models.CharField(help_text='database name', max_length=100),
        ),
        migrations.AlterField(
            model_name='db',
            name='db_port',
            field=models.IntegerField(help_text='port number'),
        ),
        migrations.AlterField(
            model_name='db',
            name='db_server',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('postgre', 'PostgreSQL'), ('oracle', 'OracleDB'), ('sql server', 'SQL Server')], help_text='select one of the options', max_length=30),
        ),
    ]
